[package]
name = "loadbalancer"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait="0.1"
once_cell = "1.21.3"
pingora = { version = "0.5", features = [ "lb" ] }
pingora-core = "0.5"
pingora-limits = "0.5.0"
pingora-load-balancing = "0.5"
pingora-proxy = "0.5"
